# Docs: https://docs.github.com/en/code-security/supply-chain-security/configuration-options-for-dependency-updates
version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
    labels:
      - 'github-actions'
    reviewers:
      - 'pioardi'
      - 'jerome-benoit'
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    labels:
      - 'dependencies'
    reviewers:
      - 'pioardi'
      - 'jerome-benoit'
    versioning-strategy: increase
  - package-ecosystem: 'npm'
    directory: '/benchmarks/versus-external-pools'
    schedule:
      interval: 'daily'
    labels:
      - 'dependencies'
      - 'benchmarks'
    reviewers:
      - 'pioardi'
      - 'jerome-benoit'
    versioning-strategy: increase
  - package-ecosystem: 'npm'
    directory: '/examples/typescript/http-client-pool'
    schedule:
      interval: 'daily'
    labels:
      - 'dependencies'
      - 'examples'
    reviewers:
      - 'pioardi'
      - 'jerome-benoit'
    versioning-strategy: increase
  - package-ecosystem: 'npm'
    directory: '/examples/typescript/smtp-client-pool'
    schedule:
      interval: 'daily'
    labels:
      - 'dependencies'
      - 'examples'
    reviewers:
      - 'pioardi'
      - 'jerome-benoit'
    versioning-strategy: increase
  - package-ecosystem: 'npm'
    directory: '/examples/typescript/http-server-pool/express-worker_threads'
    schedule:
      interval: 'daily'
    labels:
      - 'dependencies'
      - 'examples'
    reviewers:
      - 'pioardi'
      - 'jerome-benoit'
  - package-ecosystem: 'npm'
    directory: '/examples/typescript/http-server-pool/express-hybrid'
    schedule:
      interval: 'daily'
    labels:
      - 'dependencies'
      - 'examples'
    reviewers:
      - 'pioardi'
      - 'jerome-benoit'
    versioning-strategy: increase
  - package-ecosystem: 'npm'
    directory: '/examples/typescript/http-server-pool/express-cluster'
    schedule:
      interval: 'daily'
    labels:
      - 'dependencies'
      - 'examples'
    reviewers:
      - 'pioardi'
      - 'jerome-benoit'
    versioning-strategy: increase
  - package-ecosystem: 'npm'
    directory: '/examples/typescript/http-server-pool/fastify-worker_threads'
    schedule:
      interval: 'daily'
    labels:
      - 'dependencies'
      - 'examples'
    reviewers:
      - 'pioardi'
      - 'jerome-benoit'
    versioning-strategy: increase
  - package-ecosystem: 'npm'
    directory: '/examples/typescript/http-server-pool/fastify-hybrid'
    schedule:
      interval: 'daily'
    labels:
      - 'dependencies'
      - 'examples'
    reviewers:
      - 'pioardi'
      - 'jerome-benoit'
    versioning-strategy: increase
  - package-ecosystem: 'npm'
    directory: '/examples/typescript/http-server-pool/fastify-cluster'
    schedule:
      interval: 'daily'
    labels:
      - 'dependencies'
      - 'examples'
    reviewers:
      - 'pioardi'
      - 'jerome-benoit'
    versioning-strategy: increase
  - package-ecosystem: 'npm'
    directory: '/examples/typescript/websocket-server-pool/ws-worker_threads'
    schedule:
      interval: 'daily'
    labels:
      - 'dependencies'
      - 'examples'
    reviewers:
      - 'pioardi'
      - 'jerome-benoit'
    versioning-strategy: increase
  - package-ecosystem: 'npm'
    directory: '/examples/typescript/websocket-server-pool/ws-hybrid'
    schedule:
      interval: 'daily'
    labels:
      - 'dependencies'
      - 'examples'
    reviewers:
      - 'pioardi'
      - 'jerome-benoit'
    versioning-strategy: increase
  - package-ecosystem: 'npm'
    directory: '/examples/typescript/websocket-server-pool/ws-cluster'
    schedule:
      interval: 'daily'
    labels:
      - 'dependencies'
      - 'examples'
    reviewers:
      - 'pioardi'
      - 'jerome-benoit'
    versioning-strategy: increase
