# Docs: https://docs.github.com/en/code-security/supply-chain-security/configuration-options-for-dependency-updates
version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
    labels:
      - 'github-actions'
    reviewers:
      - 'pioardi'
      - 'jerome-benoit'
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    labels:
      - 'dependencies'
    reviewers:
      - 'pioardi'
      - 'jerome-benoit'
    versioning-strategy: increase
  - package-ecosystem: 'npm'
    directory: '/benchmarks/versus-external-pools'
    schedule:
      interval: 'daily'
    commit-message:
      prefix: '[benchmarks]'
    labels:
      - 'dependencies'
      - 'benchmarks'
      - 'nocombine'
    reviewers:
      - 'pioardi'
      - 'jerome-benoit'
    versioning-strategy: increase
